#ifndef INCLUDES_H
#define INCLUDES_H


#include "em_device.h"
#include "energy_micro_clk_system.h"
#include "em_emu.h"
#include "em_cmu.h"
#include "timer.h"
#include "gpio.h"
#include "date_type.h"
#include "em_timer.h"
#include "em_gpio.h"
#include "rtc.h"
#include "em_chip.h"
#include "em_rtc.h"
#include "em_leuart.h"
#include "em_dma.h"
#include "usart.h"
#include "em_usart.h"
#include "queue.h"
#include "flash.h"
#include "compiler.h"
#include "gsm.h"
#include "stdio.h"
#include "string.h"
#include "myfunction.h"
#include "gsmoperate.h"
#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "timer_conver.h"
#include "protocol.h"
#include "em_adc.h"
#include "em_wdog.h"
#include "em_rmu.h"
#include "adxl.h"
#include "spi.h"
#include "gps.h"
#include "cc3000.h"
#include "hci.h"
#include "wlan.h"
#include "cc3000_common.h"
#include "evnt_handler.h"
#include "nvmem.h"
#include "math.h"
#include "date_type.h"
#include "em_common.h"
#include "em_usb.h"
#include "usb_user.h"
#include"descriptors.h"
#include "lcd_io.h"
#include "ble.h"
#endif


